### ISSUE TITLE
Remove hardcoding of the "WRFV3" directory in the WPS 4.x.x codes. Causing compilation failures cause wrfio libraries can't be found

### ISSUE THREAD

**Issue by DonteRW** [wrf-model/WPS#95] opened 2018-11-24 04:16 UTC
I have been trying to compile WPS 4.0.2 but _ungrib.exe_ compiles and _metgrid.exe_ and _geogrid.exe_ fail to compile. The error messages in log.complie are  

 ***************************************************************************************
 Error : Not building geogrid. Check whether WRF is compiled in /home/rwasokadt1/WRF402/WPS-4.0.2/../WRFV3
 ***************************************************************************************

 ***************************************************************************************
 Error : Not building metgrid. Check whether WRF is compiled in /home/rwasokadt1/WRF402/WPS-4.0.2/../WRFV3
 ***************************************************************************************

Upon scrutiny of the log.compile file, I think this compilation failure is being caused by the fact that  the WPS codes, from version 3, have the below hard coded lines.  These hard coded lines are distributed all over the codes but _WRF_DIR2_ is wrong hence compilation failures

        if [ "" = yes ] ; then \
          WRF_DIR2=../WRFV3 ; \
        else \
          WRF_DIR2=/home/rwasokadt1/WRF402/WPS-4.0.2/../WRFV3 ; \
        fi ; \
        make -i -r ungrib.exe \
                WRF_DIR="$WRF_DIR2" \

This causes problems because now we working with version 4 codes and with git cloning/wget the folder/directory is created as WRF-4.0.x after _untarring_ and yet WPS expects the WRF folder to be **.../WRFV3** or that WRF is inside the WPS folder. Beacuse of this the wrfio files required by WPS, created when WRF is compiled, cannot be found!! 

exporting the WRF-4.0.x directory like below, does not work either!!
export WRF_DIR2=/home/rwasokadt1/WRF402/WRFV402_src

**Possible Solutions**
Change WRFV3 to WRFV4  in the WPS codes and make sure that WRF untars to WRFV4 and not WRF-4.x.x as the current case

Or allow the user to specify the path of the WRFV-4.x.x  directory. Tried this now, but its not working

**Interim Crazy Solution**
Rename the WRF 4.0.x to WRFV3, eg    $ mv WRF-4.0.2/ WRFV3

then configure WPS

and compile

then sunny days, as shown below:

$ ls -l *.exe
geogrid.exe -> geogrid/src/geogrid.exe
metgrid.exe -> metgrid/src/metgrid.exe
ungrib.exe -> ungrib/src/ungrib.exe

then    ls -ls geogrid/src/geogrid.exe
Members(Pr) 3706067 Nov 24 04:43 geogrid/src/geogrid.exe

### voilà

**Comment by mgduda** [comment] 2018-11-27 01:34
Just to make sure I understand, are you compiling WPS v3.x or WPS v4.0.2? If the latter, are you using the `configure.wps` file produced by the WPS v4.0.2 configure script, or are you copying this from your build of the WPS v3.x code? The logic for finding the WRF source directory looks like the following in the WPS v4.0.2 code:
```
#
# Look for compiled WRF code in one of several directories: WRF-4.0.2, WRF-4.0.1, WRF-4.0, WRF, and WRFV3.
# The need for complicated logic to do this arises from the various names that the WRF code may take
# on, depending on whether it was obtained through a GitHub archive file, as a clone of the GitHub
# repository, or an older WRF v3.x tar file.
# To override the path to the compiled WRF code, just set the WRF_DIR variable after the "endif" below
#
ifneq ($(wildcard $(DEV_TOP)/../WRF-4.0.2), ) # Check for WRF v4.0.2 directory (probably GitHub archive)
        WRF_DIR = ../WRF-4.0.2
else
ifneq ($(wildcard $(DEV_TOP)/../WRF-4.0.1), ) # Check for WRF v4.0.1 directory (probably GitHub archive)
        WRF_DIR = ../WRF-4.0.1
else
ifneq ($(wildcard $(DEV_TOP)/../WRF-4.0), )   # Check for WRF v4.0 directory (probably GitHub archive)
        WRF_DIR = ../WRF-4.0
else
ifneq ($(wildcard $(DEV_TOP)/../WRF), )       # Check for clone of the WRF repository
        WRF_DIR = ../WRF
else                                          # Check for old WRF v3.x directory
        WRF_DIR = ../WRFV3
endif
endif
endif
endif
```

**Comment by DonteRW** [comment] 2018-11-27 01:54
Hi

I was compiling WPS 4.0.2.

yes, i was using the configure.wps  file produced by the WPS v4.0.2 configure script.


To make it work, my top-level directory looks like what this:

rwasokadt1@linux373:~/WRF402$ ls
GEOG_WPS  v4.0.2.tar.gz  WPS-4.0.2  WPS402.tar.gz  WRFV3  


the folder/directory (re)named "WRFV3" is the directory "WRF-4.0.2" i got after, _tar -zxvf v4.0.2.tar.gz_

**Comment by mgduda** [comment] 2018-11-27 03:12
I'm not yet sure what I may be doing differently, but I'm not able to reproduce this issue locally. You mentioned in your original comment that you attempted to set
```
export WRF_DIR2=/home/rwasokadt1/WRF402/WRFV402_src
```
which suggests your WRF code is compiled in a directory named `WRFV402_src`. Can you confirm that when you try to compile the WPS v4.0.2 code you have a directory at the same level as the `WPS-4.0.2` directory named `WRF-4.0.2`? E.g., when I'm able to compile successfully, my directory structure looks like:
```
$ ls
total 0
drwxr-xr-x  7 duda mmm 440 Nov 26 20:00 WPS-4.0.2
drwxr-xr-x 22 duda mmm 580 Nov 26 19:52 WRF-4.0.2
```

**Comment by DonteRW** [comment] 2018-12-06 17:49
Hi
Umm the export statement i posted above is incomplete; my mistake, sorry

YES, i was trying compile WPS and WRF at the directory same level. In any case, if the two were at a different levels, the renaming the _WRF-4.0.2_ directory to _WRFV3_ wouldnt have worked for compiling WPS.

Looking through the other issues here, i suspect that this issue i am raising is related to this problem behind this issue as well: https://github.com/wrf-model/WPS/issues/72.  No the same exactly, but closely related

**Comment by mgduda** [comment] 2019-03-01 18:57
I'm not able to reproduce the issue you're seeing, and we haven't had any other reports of a similar issue, so I'll close this issue for now. If you encounter issues when using the latest versions (as of now, 4.0.3) of both WRF and the WPS, feel free to re-open the issue with additional details.

**Closed by mgduda** 2019-03-01 18:57 UTC
